app/api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import *

app_name = "api"

bus_router = routers.DefaultRouter()
bus_router.register(r"bus", BusViewSet, basename="bus")
trip_router = routers.DefaultRouter()
trip_router.register(r"trip", TripPartnerViewSet, basename="trip")

urlpatterns = [
    path("api/v1/user/create/", CreateUserView.as_view(), name="user-create"),
    path("api/v1/partner/create/", CreatePartnerView.as_view(), name="partner-create"),
    path("api/v1/token/", CreateTokenView.as_view(), name="token"),
    path("api/v1/user/me/", ManageUserView.as_view(), name="user-me"),
    path("api/v1/partner/me/", ManagePartnerView.as_view(), name="partner-me"),
    path("api/v1/partner/", include(bus_router.urls)),
    path("api/v1/partner/", include(trip_router.urls)),
    path("api/v1/city/", CityView.as_view(), name="city"),
    path(
        "api/v1/partner/station/",
        ListCreateStationView.as_view(),
        name="partner-station",
    ),
    path("api/v1/user/trip/", TripUserView.as_view(), name="user-trip"),
    path("api/v1/user/ticket/", ListCreateTicketUserView.as_view(), name="ticket-list"),
    path(
        "api/v1/user/ticket/<int:pk>/",
        RetrieveUpdateTicketUserView.as_view(),
        name="ticket-detail",
    ),
    path("api/v1/trip/<int:pk>/", TripView.as_view(), name="trip"),
]

app/app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)

from app import settings
from core.views import pageForbidden, AjaxGetStationsView, pageNotFound

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/v1/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    path("", include("api.urls")),
    path("", include("core.urls")),
    path("user/", include("user.urls")),
    path("partner/", include("partner.urls")),
    path("select2/", include("django_select2.urls")),
    path("ajax/get_stations/", AjaxGetStationsView.as_view(), name="ajax_get_stations"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include("debug_toolbar.urls"))] + urlpatterns

handler403 = pageForbidden
handler404 = pageNotFound

app/user/urls.py
from django.urls import path
from user.views import *

app_name = "user"

urlpatterns = [
    path("registration/", RegisterUser.as_view(), name="registration"),
    path("login/", LoginUser.as_view(), name="login"),
    path("trips/future/", user_profile, name="future"),
    path("contact/", user_contact, name="contact"),
    path("trips/history/", user_history, name="history"),
    path("ticket/<int:ticket_pk>/return/", ticket_return, name="ticket_return"),
    path("tickets/returned", user_returned_tickets, name="returned_tickets"),
    path("", logout_user, name="logout"),
]

app/user/models.py
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    PermissionsMixin,
    BaseUserManager,
)
from phonenumber_field.modelfields import PhoneNumberField
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    """Manager for users."""

    def create_user(self, phone, password=None, **extra_fields):
        """Create save and return a new user"""
        if not phone:
            raise ValueError("User must have a phone number.")
        user = self.model(phone=phone, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_superuser(self, phone, password):
        """Create and return a new superuser"""
        user = self.create_user(phone, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)

        return user


class User(AbstractBaseUser, PermissionsMixin):
    """User in the system."""

    class Meta:
        verbose_name = _("Користувач")
        verbose_name_plural = _("Користувачі")

    phone = PhoneNumberField(unique=True, verbose_name=_("Номер телефону"))
    email = models.EmailField(max_length=255, unique=True, verbose_name=_("E-mail"))
    date_joined = models.DateTimeField(
        auto_now_add=True, verbose_name=_("Дата реєстрації")
    )
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_partner = models.BooleanField(default=False)
    is_sub_account = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = "phone"

    def __str__(self):
        return str(self.phone)

app/user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import User


class RegisterClientForm(UserCreationForm):
    phone = forms.CharField(
        label=_("Телефон"),
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
            }
        ),
    )

    email = forms.EmailField(
        label=_("E-mail"),
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
            }
        ),
    )

    password1 = forms.CharField(
        label=_("Пароль"),
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
            }
        ),
    )

    password2 = forms.CharField(
        label=_("Повтор паролю"),
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
            }
        ),
    )

    class Meta:
        model = User
        fields = (
            "phone",
            "email",
            "password1",
            "password2",
        )


class AddEmailToUser(forms.ModelForm):
    class Meta:
        model = User
        fields = ["email"]
        widgets = {
            "email": forms.TextInput(
                attrs={"placeholder": "E-mail", "class": "form-control"}
            )
        }

    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email=email):
            raise ValidationError("Этот адрес электронной почты уже используется")
        return email


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label="Номер телефону",
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
            }
        ),
    )
    password = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(
            attrs={
                "class": "form-control",
            }
        ),
    )

app/user/views.py
from django.contrib.auth import logout, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic import CreateView, TemplateView, ListView
from django.utils.translation import gettext_lazy as _

from core.models import Ticket, Trip, City
from core.utils import FormInvalidMixin
from user.forms import *


class RegisterUser(FormInvalidMixin, CreateView):
    """
    View for user registration.

    Attributes:
        form_class (class): Form used for user registration.
        template_name (str): HTML template for rendering the registration form.

    Methods:
        form_valid(self, form): Handles the valid form submission, creates a new user,
                               logs in the user, and redirects to the home page.
        get_context_data(self, **kwargs): Adds additional context data for rendering the form.
    """

    form_class = RegisterClientForm
    template_name = "user/register.html"

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("core:home")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = _("Реєстрація")
        return context


class LoginUser(FormInvalidMixin, LoginView):
    """
    View for user login.

    Attributes:
        form_class (class): Form used for user login.
        template_name (str): HTML template for rendering the login form.

    Methods:
        get_success_url(self): Retrieves the URL to redirect after successful login.
        get_context_data(self, **kwargs): Adds additional context data for rendering the form.
    """

    form_class = CustomAuthenticationForm
    template_name = "user/login.html"

    def get_success_url(self):
        if not self.request.GET.get("next"):
            return reverse_lazy("core:home")
        return self.request.GET.get("next")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["next"] = ""
        if self.request.GET:
            context["next"] = self.request.GET["next"]
        context["title"] = _("Авторизація")
        return context


def logout_user(request):
    """
    View for user logout.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: Redirects to the home page after logout.
    """
    logout(request)
    return redirect("core:home")


def not_partner_required(view_func):
    """
    Decorator function to check that the user is not a partner before accessing a view.

    Args:
        view_func (function): The original view function.

    Returns:
        function: Wrapped view function with the additional check for non-partner status.
    """

    def wrapped_view(request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_partner:
            raise PermissionDenied
        return view_func(request, *args, **kwargs)

    return wrapped_view


@login_required(login_url="/user/login")
@not_partner_required
def user_returned_tickets(request):
    """
    View for displaying returned tickets for the logged-in user.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: Rendered page with returned tickets information.
    """

    tickets = Ticket.objects.filter(user=request.user, returned=True)

    return render(
        request,
        "user/returned_tickets.html",
        context={
            "tickets": tickets,
            "active_tab": "returned_tickets",
            "title": _("Повернені квитки"),
        },
    )


@login_required(login_url="/user/login")
@not_partner_required
def user_profile(request):
    """
    View for displaying the user's future trips and associated tickets.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: Rendered page with future trips and associated tickets information.
    """

    future_user_trips = (
        Ticket.objects.filter(
            user=request.user,
            trip__timedate_departure__gt=timezone.now(),
            returned=False,
        )
        .values_list("trip", flat=True)
        .distinct()
    )

    trips_with_tickets = []
    for trip in future_user_trips:
        obj = Trip.objects.get(pk=trip)
        tickets = Ticket.objects.filter(user=request.user, trip=trip, returned=False)
        trips_with_tickets.append({"trip": obj, "tickets": tickets})

    return render(
        request,
        "user/profile.html",
        context={
            "future_trips_with_tickets": trips_with_tickets,
            "active_tab": "future",
            "href": "user:future",
            "title": _("Майбутні поїздки"),
        },
    )


@login_required(login_url="/user/login")
@not_partner_required
def user_contact(request):
    """
    View for handling user contact information.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: Rendered page for updating user contact information.
    """

    if request.method == "POST":
        form = AddEmailToUser(request.POST, instance=request.user)
        if form.is_valid():
            user = request.user
            user.email = form.cleaned_data["email"]
            user.save()
            return redirect("user:contact")
    else:
        form = AddEmailToUser(instance=request.user)

    return render(
        request,
        "user/contact.html",
        context={
            "form": form,
            "active_tab": "contact",
            "title": _("Контактна інформація"),
        },
    )


@login_required(login_url="/user/login")
@not_partner_required
def user_history(request):
    """
    View for displaying the user's past trips and associated tickets.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: Rendered page with past trips and associated tickets information.
    """

    trips_with_tickets = []
    sort_type = request.GET.get("sort_type", None)
    if sort_type:
        if sort_type == "ASC":
            sort = "trip__timedate_departure"
        else:
            sort = "-trip__timedate_departure"
        user_past_trips = (
            Ticket.objects.filter(
                user=request.user,
                trip__timedate_departure__lt=timezone.now(),
                returned=False,
            )
            .values_list("trip", flat=True)
            .distinct()
        ).order_by(sort)
    else:
        user_past_trips = (
            Ticket.objects.filter(
                user=request.user,
                trip__timedate_departure__lt=timezone.now(),
                returned=False,
            )
            .values_list("trip", flat=True)
            .distinct()
        )

    for trip in user_past_trips:
        obj = Trip.objects.get(pk=trip)
        tickets = Ticket.objects.filter(user=request.user, trip=trip, returned=False)
        trips_with_tickets.append({"trip": obj, "tickets": tickets})

    return render(
        request,
        "user/history.html",
        context={
            "past_trips_with_tickets": trips_with_tickets,
            "active_tab": "history",
            "href": "user:history",
            "sort_type": sort_type,
            "title": _("Минулі поїздки"),
        },
    )


@login_required(login_url="/user/login")
@not_partner_required
def ticket_return(request, ticket_pk):
    """
    View for handling the return of a user's ticket.

    Args:
        request (HttpRequest): The HTTP request object.
        ticket_pk (int): The primary key of the ticket to be returned.

    Returns:
        HttpResponse: Rendered page for ticket return confirmation or denial.
    """

    ticket = get_object_or_404(Ticket, pk=ticket_pk)
    if ticket.trip.timedate_departure < timezone.now():
        raise PermissionDenied()
    if request.method == "POST":
        if not ticket.returned:
            ticket.returned = True
            ticket.save()
            return render(
                request,
                "user/confirm_return.html",
                {
                    "ticket": ticket,
                    "title": _(f"Повернення білета №{ticket_pk}"),
                },
            )
        else:
            return render(
                request,
                "user/already_returned.html",
                {
                    "ticket": ticket,
                    "title": _(f"Повернення білета №{ticket_pk}"),
                },
            )

    return render(
        request,
        "user/ticket_return.html",
        context={
            "ticket_pk": ticket_pk,
            "ticket": ticket,
            "title": _(f"Повернення білета №{ticket_pk}"),
        },
    )

app/user/templates/user/already_returned.html
{% extends 'user/base.html'%}
{% block content%}
<div class="container mt-5">
    <div class="row">
        <div class="col d-flex justify-content-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="5em" height="5em" fill="currentColor" class="bi bi-ban" viewBox="0 0 16 16">
                <path d="M15 8a6.97 6.97 0 0 0-1.71-4.584l-9.874 9.875A7 7 0 0 0 15 8M2.71 12.584l9.874-9.875a7 7 0 0 0-9.874 9.874ZM16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0"/>
            </svg>
        </div>
    </div>
    <div class="row">
        <div class="col d-flex justify-content-center">
            <span class="fs-2 fw-bold">Білет вже повернено</span>
        </div>
    </div>
</div>
{% endblock %}

app/user/templates/user/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load bootstrap5 %}
    {% load static %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link type="text/css" href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    <title>{{title}}</title>
</head>
<body>
    {% include 'partials/nav-bar.html'%}
    {% if user.is_authenticated %}
        <div class="container">
            <div class="row">
              <div class="col">
                  <nav class="navbar navbar-expand-lg navbar-light">
                      <div class="container-fluid p-0">
                          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                              <li><a class="nav-link {% if active_tab == 'future' %}active border-bottom border-dark border-2{% endif %}" href="{% url 'user:future' %}">Майбутні поїздки</a></li>
                              <li><a class="nav-link {% if active_tab == 'history' %}active border-bottom border-dark border-2{% endif %}" href="{% url 'user:history' %}">Історія поїздок</a></li>
                              <li><a class="nav-link {% if active_tab == 'contact' %}active border-bottom border-dark border-2{% endif %}" href="{% url 'user:contact' %}">Контактна інформація</a></li>
                              <li><a class="nav-link {% if active_tab == 'returned_tickets' %}active border-bottom border-dark border-2{% endif %}" href="{% url 'user:returned_tickets' %}">Повернені квитки</a></li>
                          </ul>
                      </div>
                  </nav>
              </div>
            </div>
        </div>
    {% endif %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

app/user/templates/user/confirm_return.html
{% extends 'user/base.html'%}
{% block content%}
<div class="container mt-5">
    <div class="row">
        <div class="col d-flex justify-content-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="5em" height="5em" fill="currentColor"
                 class="bi bi-check-circle-fill" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0m-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
            </svg>
        </div>
    </div>
    <div class="row">
        <div class="col d-flex justify-content-center">
            <span class="fs-2 fw-bold">Білет успішно повернено!</span>
        </div>
    </div>
</div>
{% endblock %}

app/user/templates/user/contact.html
{% extends  'user/base.html' %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col shadow-sm p-3 bg-body rounded">
            <div class="row">
                <div class="col"><span class="text-muted">Телефен:</span> {{user.phone}}</div>
            </div>
            <div class="row">
                <div class="col">
                    <span class="text-muted">Пошта:</span> {{user.email}}
                </div>
            </div>
        </div>
        <div class="col shadow-sm p-3 ms-3 bg-body rounded">
            <form method="POST" action="{% url 'user:contact'%}">
                {% csrf_token %}
                <div>{{ form.non_field_errors }}</div>
                {% for f in form %}
                    <div class="col">
                        <div class="form-floating">
                            {{ f }}
                            <label for="floatingInputGrid">Змінити пошту:</label>
                        </div>
                    </div>
                    {% endfor %}
                <button class="btn btn-danger btn-sm mt-2" type="submit">Зберегти</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/user/templates/user/history.html
{% extends  'user/base.html' %}

{% block content %}
{% if past_trips_with_tickets%}
<div class="row">
    <div class="col">
        <h3 class="mt-2">Історія поїздок</h3>
    </div>
    <div class="col">
        {% include 'core/includes/sort.html'%}
    </div>
</div>
{% for dict in past_trips_with_tickets %}
    {% include 'user/includes/ticket_profile.html' with dict=dict return_ticket=False%}
{% endfor %}
{% else %}
<div class="row mt-5">
    <div class="col d-flex justify-content-center text-muted">
        <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-calendar-x" viewBox="0 0 16 16">
            <path d="M6.146 7.146a.5.5 0 0 1 .708 0L8 8.293l1.146-1.147a.5.5 0 1 1 .708.708L8.707 9l1.147 1.146a.5.5 0 0 1-.708.708L8 9.707l-1.146 1.147a.5.5 0 0 1-.708-.708L7.293 9 6.146 7.854a.5.5 0 0 1 0-.708"/>
            <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4z"/>
        </svg>
    </div>
</div>
<div class="row mt-2">
    <div class="col d-flex justify-content-center text-muted">Упс... Тут немає поїздок</div>
</div>
{% endif %}
{% endblock %}

app/user/templates/user/login.html
{% extends  'user/base.html' %}

{% block content %}
<div class="container mt-4">
    {% if next %}
    <form action="{% url 'user:login'%}?next={{next}}" method="post" novalidate>
    {% else %}
    <form action="{% url 'user:login'%}" method="post" novalidate>
    {% endif %}
        {% csrf_token %}
        {% include 'core/includes/all_form_error.html'%}
        {% for field in form %}
            <div class="row d-flex justify-content-center">
                <div class="col-4">
                    <label class="form-label mt-2" for={{field.name}}>{{field.label}}</label>
                    <span id={{field.name}}>{{field}}</span>
                    {% if field.name in form.errors.keys %}
                        <div class="text-danger small">
                            {% for f, errors in form.errors.items %}
                                {% if f == field.name %}
                                    {% for error in errors %}
                                        {{error}}
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <div class="row mt-4 d-flex justify-content-center">
            <div class="d-grid col-4">
                <button type="submit" class="btn btn-block btn-danger text-light">Увійти</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

app/user/templates/user/profile.html
{% extends  'user/base.html' %}

{% block content %}
{% if future_trips_with_tickets%}
<div class="row">
    <div class="col">
        <h3 class="mt-2">Майбутні поїздки</h3>
    </div>
    <div class="col">
        {% include 'core/includes/sort.html'%}
    </div>
</div>
{% for dict in future_trips_with_tickets %}
    {% include 'user/includes/ticket_profile.html' with dict=dict return_ticket=True%}
{% endfor %}
{% else %}
<div class="row mt-5">
    <div class="col d-flex justify-content-center text-muted">
        <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-calendar-x" viewBox="0 0 16 16">
            <path d="M6.146 7.146a.5.5 0 0 1 .708 0L8 8.293l1.146-1.147a.5.5 0 1 1 .708.708L8.707 9l1.147 1.146a.5.5 0 0 1-.708.708L8 9.707l-1.146 1.147a.5.5 0 0 1-.708-.708L7.293 9 6.146 7.854a.5.5 0 0 1 0-.708"/>
            <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4z"/>
        </svg>
    </div>
</div>
<div class="row mt-2">
    <div class="col d-flex justify-content-center text-muted">Упс... Тут немає поїздок</div>
</div>
{% endif %}
{% endblock %}

app/user/templates/user/register.html
{% extends  'user/base.html' %}

{% block content %}
<div class="container mt-4">
    <form method="post" novalidate>
        {% csrf_token %}
        {% include 'core/includes/all_form_error.html'%}
        {% for field in form %}
            <div class="row d-flex justify-content-center">
                <div class="col-4">
                    <label class="form-label mt-2" for={{field.name}}>{{field.label}}</label>
                    <span id={{field.name}}>{{field}}</span>
                    {% if field.name in form.errors.keys %}
                        <div class="text-danger small">
                            {% for f, errors in form.errors.items %}
                                {% if f == field.name %}
                                    {% for error in errors %}
                                        {{error}}
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
        {% endfor %}
        <div class="row mt-4 d-flex justify-content-center">
            <div class="d-grid col-4">
                <button type="submit" class="btn btn-block btn-danger text-light">Реєстрація</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

app/user/templates/user/ticket_return.html
{% extends 'user/base.html'%}
{% block content%}
<div class="container mt-4 rounded shadow-sm bg-body">
    <div class="row">
        <div class="col d-flex justify-content-center mt-3">
            <span class="fw-bold fs-5">Повернення білета №{{ticket.pk}}</span>
        </div>
    </div>
    <div class="row mt-2">
        <div class="row">
            <div class="col">
                <span>
                    Рейс <span class="fw-bold">{{ticket.trip.start_point.city}}</span> - <span
                        class="fw-bold">{{ticket.trip.end_point.city}}</span>, на <span class="fw-bold">{{ticket.trip.timedate_departure}}</span>
                </span>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col">
                Час в дорозі: <span class="fw-light">{{ticket.trip.timedate_arrival|timeuntil:ticket.trip.timedate_departure}}</span>
            </div>
        </div>
        <div class="row">
            <div class="col-1">
                <span class="fw-bold">{{ticket.trip.timedate_departure|time}}</span>
            </div>
            <div class="col">
                <span class="fw-bold">{{ticket.trip.start_point.city}}</span>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col-1">
                <span class="fw-light">{{ticket.trip.timedate_departure | date:"j b."}}</span>
            </div>
            <div class="col">
                <span class="fw-light">
                    {{ticket.trip.departure_station.station}}
                    {{ticket.trip.departure_station.street_type|lower}}
                    {{ticket.trip.departure_station.street}},
                    {{ticket.trip.departure_station.number}}
                </span>
            </div>
        </div>
        <div class="row">
            <div class="col-1">
                <span class="fw-bold">{{ticket.trip.timedate_arrival|time}}</span>
            </div>
            <div class="col">
                <span class="fw-bold">{{ticket.trip.end_point.city}}</span>
            </div>
        </div>
        <div class="row mb-4">
            <div class="col-1">
                <span class="fw-light">{{ticket.trip.timedate_arrival| date:"j b."}}</span>
            </div>
            <div class="col">
                <span class="fw-light">
                    {{ticket.trip.arrival_station.station}}
                    {{ticket.trip.arrival_station.street_type|lower}}
                    {{ticket.trip.arrival_station.street}},
                    {{ticket.trip.arrival_station.number}}
                </span>
            </div>
        </div>
        <div class="row mb-3">
            <div class="col">
                Пасажир: <span class="fw-bold">{{ticket.last_name}} {{ticket.first_name}}</span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col mb-3 d-flex justify-content-center">
            <form method="post" action="{% url 'user:ticket_return' ticket_pk=ticket_pk %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-block btn-danger text-light mx-3">Здати білет</button>
                <a href="{% url 'user:future'%}"><button type="button" class="btn btn-block btn-danger text-light mx-3">Відмовитись</button></a>
            </form>
        </div>
    </div>
</div>
{% endblock %}