app/api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import *

app_name = "api"

bus_router = routers.DefaultRouter()
bus_router.register(r"bus", BusViewSet, basename="bus")
trip_router = routers.DefaultRouter()
trip_router.register(r"trip", TripPartnerViewSet, basename="trip")

urlpatterns = [
    path("api/v1/user/create/", CreateUserView.as_view(), name="user-create"),
    path("api/v1/partner/create/", CreatePartnerView.as_view(), name="partner-create"),
    path("api/v1/token/", CreateTokenView.as_view(), name="token"),
    path("api/v1/user/me/", ManageUserView.as_view(), name="user-me"),
    path("api/v1/partner/me/", ManagePartnerView.as_view(), name="partner-me"),
    path("api/v1/partner/", include(bus_router.urls)),
    path("api/v1/partner/", include(trip_router.urls)),
    path("api/v1/city/", CityView.as_view(), name="city"),
    path(
        "api/v1/partner/station/",
        ListCreateStationView.as_view(),
        name="partner-station",
    ),
    path("api/v1/user/trip/", TripUserView.as_view(), name="user-trip"),
    path("api/v1/user/ticket/", ListCreateTicketUserView.as_view(), name="ticket-list"),
    path(
        "api/v1/user/ticket/<int:pk>/",
        RetrieveUpdateTicketUserView.as_view(),
        name="ticket-detail",
    ),
    path("api/v1/trip/<int:pk>/", TripView.as_view(), name="trip"),
]

app/app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)

from app import settings
from core.views import pageForbidden, AjaxGetStationsView, pageNotFound

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/v1/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    path("", include("api.urls")),
    path("", include("core.urls")),
    path("user/", include("user.urls")),
    path("partner/", include("partner.urls")),
    path("select2/", include("django_select2.urls")),
    path("ajax/get_stations/", AjaxGetStationsView.as_view(), name="ajax_get_stations"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include("debug_toolbar.urls"))] + urlpatterns

handler403 = pageForbidden
handler404 = pageNotFound

app/partner/urls.py
from django.urls import path
from partner.views import *

app_name = "partner"

urlpatterns = [
    path("profile/", PartnerProfileView.as_view(), name="profile"),
    path("bus/list/", BusView.as_view(), name="buses"),
    path("bus/create/", CreateBusView.as_view(), name="bus_create"),
    path("trips/", TripView.as_view(), name="trips"),
    path("trip/create/", CreateTripView.as_view(), name="trip_create"),
    path("trip/<int:trip_pk>/update/", UpdateTripView.as_view(), name="trip_update"),
    path("registration/", partner_registration, name="registration"),
    path("sub_accounts/", SubAccountsView.as_view(), name="sub_accounts"),
    path(
        "sub_account_create/",
        partner_subaccount_registration,
        name="sub_account_create",
    ),
    path("station/create/", StationCreateView.as_view(), name="station_create"),
    path("station/list/", StationListView.as_view(), name="station_list"),
]

app/user/urls.py
from django.urls import path
from user.views import *

app_name = "user"

urlpatterns = [
    path("registration/", RegisterUser.as_view(), name="registration"),
    path("login/", LoginUser.as_view(), name="login"),
    path("trips/future/", user_profile, name="future"),
    path("contact/", user_contact, name="contact"),
    path("trips/history/", user_history, name="history"),
    path("ticket/<int:ticket_pk>/return/", ticket_return, name="ticket_return"),
    path("tickets/returned", user_returned_tickets, name="returned_tickets"),
    path("", logout_user, name="logout"),
]

app/partner/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.db import transaction
from django.db.models import Count, Sum, Min, Max
from django.shortcuts import render, redirect
from django.utils import timezone
from django.views import View
from slugify import slugify
from django.utils.translation import gettext_lazy as _
from django.views.generic import ListView, CreateView, UpdateView

from core.models import Company, Bus, Partner, Trip, Ticket, Station
from core.utils import PartnerRequiredMixin, FormInvalidMixin
from partner.forms import (
    CreateBusForm,
    CompanyForm,
    CreateUpdateTripForm,
    StationCreateFrom,
    TripSearchForm,
)
from user.forms import RegisterClientForm


@transaction.atomic
def partner_registration(request):
    """
    View for handling partner registration.

    This view processes the registration of a partner, which includes creating a new user,
    associating them with a company, and logging them in.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object.

    Raises:
        Exception: An error occurred during registration.

    """
    if request.method == "POST":
        user_form = RegisterClientForm(request.POST)
        company_form = CompanyForm(request.POST)
        if user_form.is_valid() and company_form.is_valid():
            try:
                user = user_form.save(commit=False)
                user.is_partner = True
                user.save()
                company = company_form.save(commit=False)
                company.slug = slugify(company.company_name)
                company.save()
                Partner.objects.create(user=user, company=company)
                login(request, user)
                return redirect("partner:profile")
            except Exception as e:
                print(f"Error during registration: {e}")
                messages.error(
                    request, "An error occurred during registration. Please try again."
                )
                transaction.set_rollback(True)
        else:
            for key, value in user_form.errors.items():
                if key != "__all__":
                    user_form.fields[key].widget.attrs[
                        "class"
                    ] = "form-control is-invalid"
            for key, value in company_form.errors.items():
                if key != "__all__":
                    company_form.fields[key].widget.attrs[
                        "class"
                    ] = "form-control is-invalid"

    else:
        user_form = RegisterClientForm()
        company_form = CompanyForm()

    return render(
        request,
        "partner/registration.html",
        context={
            "user_form": user_form,
            "company_form": company_form,
            "title": _("Реєстрація"),
        },
    )


@transaction.atomic
def partner_subaccount_registration(request):
    """
    View for handling partner sub-account registration.

    This view processes the registration of a partner sub-account, creating a new user
    associated with the same company as the logged-in partner.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response object.

    Raises:
        Exception: An error occurred during registration.

    """
    if request.method == "POST":
        user_form = RegisterClientForm(request.POST)
        if user_form.is_valid():
            try:
                user = user_form.save(commit=False)
                user.is_partner = True
                user.is_sub_account = True
                user.save()
                Partner.objects.create(
                    user=user,
                    company=Company.objects.get(partner__user=request.user),
                )
                return redirect("partner:sub_accounts")
            except Exception as e:
                print(f"Error during registration: {e}")
                messages.error(
                    request, "An error occurred during registration. Please try again."
                )
                transaction.set_rollback(True)
        else:
            for key, value in user_form.errors.items():
                if key != "__all__":
                    user_form.fields[key].widget.attrs[
                        "class"
                    ] = "form-control is-invalid"
    else:
        user_form = RegisterClientForm()

    return render(
        request,
        "partner/sub_account_registration.html",
        context={"user_form": user_form, "title": _("Реєстрація")},
    )


class PartnerProfileView(PartnerRequiredMixin, View):
    """
    View for displaying the partner's profile information.

    This view requires the user to be logged in as a partner. It retrieves the associated
    company based on the logged-in user and renders the partner's profile page.

    Attributes:
        template_name (str): The template name for rendering the profile page.

    Methods:
        get(self, request): Handles GET requests to display the partner's profile page.

    """

    template_name = "partner/profile.html"

    def get(self, request):
        """
        Handles GET requests to display the partner's profile page.

        Args:
            request (HttpRequest): The HTTP request object.

        Returns:
            HttpResponse: The HTTP response object containing the partner's profile page.

        """
        company = Company.objects.get(partner__user=request.user)
        return render(
            request,
            "partner/profile.html",
            context={
                "company": company,
                "active_tab": "profile",
                "title": _("Контактна інформація"),
            },
        )


class BusView(PartnerRequiredMixin, ListView):
    """
    View for displaying a list of buses along with additional statistics.

    This view requires the user to be logged in as a partner and provides information about each bus,
    including revenue, ticket prices, and trip counts.

    Attributes:
        model (Model): The model associated with this view.
        template_name (str): The template name for rendering the bus list page.
        context_object_name (str): The context variable name for the list of buses.

    Methods:
        get_queryset(self): Retrieve the queryset of buses associated with the logged-in partner.
        get_context_data(self, **kwargs): Add additional context data to be used in the template.
        get_revenue_dict(self, bus_list): Calculate revenue for each bus in the provided list.
        add_revenue_to_bus(self, bus_list): Add revenue information to each bus in the list.
        get_ticket_price_dict(self, bus_list): Calculate ticket price statistics for each bus.
        add_ticket_price_to_bus(self, bus_list): Add ticket price information to each bus in the list.
        get_past_trip_count_dict(self, bus_list): Calculate past trip counts for each bus.
        get_future_trip_count_dict(self, bus_list): Calculate future trip counts for each bus.
        add_trip_counts_to_bus(self, bus_list): Add trip count information to each bus in the list.
        get_future_trip_dict(self, bus_list): Retrieve future trips for each bus in the provided list.
        add_future_trip_to_bus(self, bus_list): Add future trip information to each bus in the list.
        get_past_trip_dict(self, bus_list): Retrieve past trips for each bus in the provided list.
        add_past_trip_to_bus(self, bus_list): Add past trip information to each bus in the list.

    """

    model = Bus
    template_name = "partner/bus_list.html"
    context_object_name = "bus_list"

    def get_queryset(self):
        """
        Retrieve the queryset of buses associated with the logged-in partner.

        Returns:
            QuerySet: The queryset of buses associated with the logged-in partner.

        """
        licence_plate = self.request.GET.get("licence_plate", "")

        if licence_plate:
            return Bus.objects.select_related("company").filter(
                company__partner__user=self.request.user, licence_plate=licence_plate
            )
        return Bus.objects.select_related("company").filter(
            company__partner__user=self.request.user
        )

    def get_context_data(self, **kwargs):
        """
        Add additional context data to be used in the template.

        Returns:
            dict: Additional context data.
        """
        context = super().get_context_data(**kwargs)
        context["active_tab"] = "bus"
        context["licence_plate_value"] = self.request.GET.get("licence_plate", "")
        context["title"] = _("Автобуси")

        bus_list = context["bus_list"]
        self.add_trip_counts_to_bus(bus_list)
        self.add_ticket_price_to_bus(bus_list)
        self.add_revenue_to_bus(bus_list)
        self.add_future_trip_to_bus(bus_list)
        self.add_past_trip_to_bus(bus_list)

        return context

    def get_future_trip_dict(self, bus_list):
        return {
            bus.pk: Trip.objects.filter(
                bus=bus, timedate_departure__gt=timezone.now()
            ).order_by("timedate_departure")
            for bus in bus_list
        }

    def add_future_trip_to_bus(self, bus_list):
        future_trip_dict = self.get_future_trip_dict(bus_list)

        for bus in bus_list:
            for trip in future_trip_dict[bus.pk]:
                bought_seats = Ticket.objects.filter(trip=trip, returned=False).count()
                trip.bought_seats = bought_seats
            bus.future_trips = future_trip_dict[bus.pk]

    def get_past_trip_dict(self, bus_list):
        return {
            bus.pk: Trip.objects.filter(
                bus=bus, timedate_departure__lt=timezone.now()

app/partner/templates/partner/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load bootstrap5 %}
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <link type="text/css" href="{% static 'core/css/styles.css' %}" rel="stylesheet" />
    <title>{{title}}</title>
</head>
<body>
    {% include 'partials/nav-bar.html'%}
    {% if user.is_authenticated %}
        <div class="container">
            <div class="row">
              <div class="col">
                  <nav class="navbar navbar-expand-lg navbar-light">
                      <div class="container-fluid p-0">
                          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                              <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle {% if active_tab == 'bus' %}active border-bottom border-dark border-2{% endif %}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        <span>Автобуси</span>
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li><a class="dropdown-item" href="{% url 'partner:bus_create'%}">Додати атобус</a></li>
                                        <li><a class="dropdown-item" href="{% url 'partner:buses' %}">Переглянути наявні</a></li>
                                    </ul>
                              </li>
                              <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle {% if active_tab == 'trips' %}active border-bottom border-dark border-2{% endif %}" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                        <span>Рейси</span>
                                    </a>
                                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                        <li><a class="dropdown-item" href="{% url 'partner:trip_create'%}">Додати рейс</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" href="{% url 'partner:trips' %}?type=future">Майбутні рейси</a></li>
                                        <li><a class="dropdown-item" href="{% url 'partner:trips' %}?type=past">Минулі рейси</a></li>
                                        <li><hr class="dropdown-divider"></li>
                                        <li><a class="dropdown-item" href="{% url 'partner:station_list'%}">Список станцій</a></li>
                                        <li><a class="dropdown-item" href="{% url 'partner:station_create'%}">Додати станцію</a></li>
                                    </ul>
                              </li>
                              <li><a class="nav-link {% if active_tab == 'profile' %}active border-bottom border-dark border-2{% endif %}" href="{% url 'partner:profile' %}">Контактна інформація</a></li>
                              {% if not user.is_sub_account %}
                                <li><a class="nav-link {% if active_tab == 'sub_accounts' %}active border-bottom border-dark border-2{% endif %}" href="{% url 'partner:sub_accounts' %}">Суб-аккаунти</a></li>
                              {% endif %}
                          </ul>
                      </div>
                  </nav>
              </div>
            </div>
        </div>
    {% endif %}
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

app/partner/templates/partner/bus_list.html
{% extends  'partner/base.html' %}

{% block content %}
    {% if bus_list or request.GET.licence_plate%}
        <div class="container p-3 rounded shadow-sm bg-body">
            <div class="row">
                <div class="col">
                    <form method="get" action="{% url 'partner:buses' %}">
                        <div class="row">
                            <div class="col">
                                <input
                                        type="text"
                                        name="licence_plate"
                                        class="form-control"
                                        value="{{ licence_plate_value }}"
                                        placeholder="Номерний знак"
                                        onkeypress="return event.charCode != 32"/>
                            </div>
                            <div class="col d-flex justify-content-start">
                                <button type="submit" class="btn btn-danger">Знайти</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col d-flex justify-content-end ">
                    <a href="{% url 'partner:buses'%}"><button class="btn btn-danger">Прибрати фільтрування</button></a>
                </div>
            </div>
        </div>
        {% for bus in bus_list %}
            <div class="container p-0 border rounded shadow-sm mt-4 mb-4">
                <div class="container p-3 rounded-top bg-body">
                    <div class="row">
                        <div class="col-3 border-end">
                            <div class="row">
                                <div class="col">
                                    <span class="badge bg-light border border-dark text-black fs-2">{{bus.licence_plate}}</span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col mt-2 d-flex justify-content-start">
                                    <span class="badge bg-dark">{{bus.brand}}</span>
                                </div>
                                <div class="col mt-2 d-flex justify-content-end">
                                    <span class="badge bg-dark">{{bus.number_of_seats}}</span>
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row">
                                <div class="col">
                                    <span class="fw-bold">Ціна на білет</span>
                                </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        Середня: {{bus.average_ticket_price}} UAH
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        Мінімальна: {{bus.min_ticket_price}} UAH
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col">
                                        Максимальна: {{bus.max_ticket_price}} UAH
                                    </div>
                                </div>
                        </div>
                        <div class="col">
                            <div class="row">
                                <div class="col">
                                    <span class="fw-bold">Поїздки</span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    Минулі поїздки: {{bus.past_trip_count}}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    Майбутні поїздки: {{bus.future_trip_count}}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    Всього: {{bus.trip_count}}
                                </div>
                            </div>
                        </div>
                        <div class="col">
                            <div class="row">
                                <div class="col">
                                    <span class="fw-bold">Прибуток</span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col">
                                    Прибуток: {{bus.revenue}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="container px-3 py-1 rounded-bottom bg-light"> <!-- Информация про рейсы -->
                    <div class="col d-flex justify-content-end">
                        <a class="dropdown-toggle text-danger" data-bs-toggle="collapse" href="#detail{{forloop.counter}}" role="button" aria-expanded="false" aria-controls="collapseExample" style="text-decoration: none">
                            Рейси
                        </a>
                    </div>
                </div>
                <div class="collapse" id="detail{{forloop.counter}}"> <!-- Рейси -->
                    <div class="card-body bg-body rounded-bottom">
                <ul style="list-style-type: none; padding: 0px">
                    <ul class="nav nav-pills mb-2" id="pills-tab" role="tablist">
                        <li class="nav-item" role="presentation">
                            <button class="nav-link active" id="pills-future-tab" data-bs-toggle="pill" data-bs-target="#pills-future{{forloop.counter}}" type="button" role="tab" aria-controls="pills-route" aria-selected="true">Майбутні рейси</button>
                        </li>
                        <li class="nav-item" role="presentation">
                            <button class="nav-link" id="pills-past-tab" data-bs-toggle="pill" data-bs-target="#pills-past{{forloop.counter}}" type="button" role="tab" aria-controls="pills-carrier" aria-selected="false">Минулі рейси</button>
                        </li>
                    </ul>
                    <div class="tab-content" id="pills-tabContent">
                        <div class="tab-pane fade show active" id="pills-future{{forloop.counter}}" role="tabpanel" aria-labelledby="pills-route-tab"> <!-- Вкладка Майбутні Рейси -->
                            {% include 'partner/includes/trips_buses.html' with trips=bus.future_trips%}
                        </div>
                        <div class="tab-pane fade" id="pills-past{{forloop.counter}}" role="tabpanel" aria-labelledby="pills-route-tab"> <!-- Вкладка Майбутні Рейси -->
                            {% include 'partner/includes/trips_buses.html' with trips=bus.past_trips%}
                        </div>
                    </div>
                </ul>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
    <div class="row">
        <div class="col d-flex justify-content-center mt-3">
            <span class="fs-4 fw-bold">Тут можуть бути ваші Автобуси</span>
        </div>
    </div>
    <div class="row">
        <div class="col d-flex justify-content-center mt-3">
            <a href="{% url 'partner:bus_create' %}"><button class="btn btn-danger text-light">Додати атобус</button></a>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

app/partner/templates/partner/trip_create.html
{% extends  'partner/base.html' %}
{% load static %}
{% block content %}
<form method="post" action="{% url 'partner:trip_create'%}" novalidate>
    {% csrf_token %}
    {% include 'core/includes/all_form_error.html'%}

    <div class="row mt-3 mb-3">
        <div class="col">
            <label class="form-label" for="bus">{{form.bus.label}}</label>
            <span>{{form.bus}}</span>
        </div>
        <div class="col">
            <label class="form-label" for="price">{{form.price.label}}</label>
            <span>{{form.price}}</span>
        </div>
    </div>
    <div class="row mt-3 mb-3">
        <div class="col">
            <label class="form-label" for="start_point">{{form.start_point.label}}</label>
            <span>{{form.start_point}}</span>
        </div>
        <div class="col">
            <label class="form-label" for="departure_station">{{form.departure_station.label}}</label>
            <span>{{form.departure_station}}</span>

        </div>
        <div class="col">
            <label class="form-label" for="timedate_departure">{{form.timedate_departure.label}}</label>
            <span>{{form.timedate_departure}}</span>
        </div>
    </div>
    <div class="row mt-3 mb-3">
        <div class="col">
            <label class="form-label" for="end_point">{{form.end_point.label}}</label>
            <span>{{form.end_point}}</span>
        </div>
        <div class="col">
            <label class="form-label" for="arrival_station">{{form.arrival_station.label}}</label>
            <span aria-describedby="stationHelpBlock">{{form.arrival_station}}</span>
            <div id="stationHelpBlock" class="form-text">
                Не бачите потрібну станцію? <a href="{% url 'partner:station_create'%}" style="color: #6c757d;">Створіть її</a>.
                <br> *Дані внесені в форму не збережуться
            </div>
        </div>
        <div class="col">
            <label class="form-label" for="timedate_arrival">{{form.timedate_arrival.label}}</label>
            <span>{{form.timedate_arrival}}</span>
        </div>
    </div>

    <div class="row">
        <div class="col d-flex justify-content-end">
            <button type="submit" class="btn btn-danger text-light">Створити</button>
        </div>
    </div>

</form>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'core/js/create_trip_form.js' %}"></script>
{{ form.media }}
{% endblock %}

app/partner/templates/partner/trip_update.html
{% extends  'partner/base.html' %}
{% load static %}
{% block content %}
<form method="post" action="{% url 'partner:trip_update' trip_pk=trip.pk%}">
    {% csrf_token %}
    {{ form.non_field_errors }}

    <div class="row mt-3 mb-3">
        <div class="col">
            <label class="form-label" for="bus">{{form.bus.label}}</label>
            <span>{{form.bus}}</span>
        </div>
        <div class="col">
            <label class="form-label" for="price">{{form.price.label}}</label>
            <span>{{form.price}}</span>
        </div>
    </div>
    <div class="row mt-3 mb-3">
        <div class="col">
            <label class="form-label" for="start_point">{{form.start_point.label}}</label>
            <span>{{form.start_point}}</span>
        </div>
        <div class="col">
            <label class="form-label" for="departure_station">{{form.departure_station.label}}</label>
            <span>{{form.departure_station}}</span>

        </div>
        <div class="col">
            <label class="form-label" for="timedate_departure">{{form.timedate_departure.label}}</label>
            <span>{{form.timedate_departure}}</span>
        </div>
    </div>
    <div class="row mt-3 mb-3">
        <div class="col">
            <label class="form-label" for="end_point">{{form.end_point.label}}</label>
            <span>{{form.end_point}}</span>
        </div>
        <div class="col">
            <label class="form-label" for="arrival_station">{{form.arrival_station.label}}</label>
            <span aria-describedby="stationHelpBlock">{{form.arrival_station}}</span>
            <div id="stationHelpBlock" class="form-text">
                Не бачите потрібну станцію? <a href="{% url 'partner:station_create'%}" style="color: #6c757d;">Створіть її</a>.
                <br> *Дані внесені в форму не збережуться
            </div>
        </div>
        <div class="col">
            <label class="form-label" for="timedate_arrival">{{form.timedate_arrival.label}}</label>
            <span>{{form.timedate_arrival}}</span>
        </div>
    </div>
    <div class="row">
        <div class="col d-flex justify-content-end">
            <button type="submit" class="btn btn-danger text-light ">Оновити дані</button>
            <a href="{% url 'partner:trips'%}?type=future"><button type="button" class="btn btn-danger text-light ms-4">Відміна редагування</button></a>
        </div>
    </div>
</form>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'core/js/create_trip_form.js' %}"></script>
    {{form.media}}
{% endblock %}