app/api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import *

app_name = "api"

bus_router = routers.DefaultRouter()
bus_router.register(r"bus", BusViewSet, basename="bus")
trip_router = routers.DefaultRouter()
trip_router.register(r"trip", TripPartnerViewSet, basename="trip")

urlpatterns = [
    path("api/v1/user/create/", CreateUserView.as_view(), name="user-create"),
    path("api/v1/partner/create/", CreatePartnerView.as_view(), name="partner-create"),
    path("api/v1/token/", CreateTokenView.as_view(), name="token"),
    path("api/v1/user/me/", ManageUserView.as_view(), name="user-me"),
    path("api/v1/partner/me/", ManagePartnerView.as_view(), name="partner-me"),
    path("api/v1/partner/", include(bus_router.urls)),
    path("api/v1/partner/", include(trip_router.urls)),
    path("api/v1/city/", CityView.as_view(), name="city"),
    path(
        "api/v1/partner/station/",
        ListCreateStationView.as_view(),
        name="partner-station",
    ),
    path("api/v1/user/trip/", TripUserView.as_view(), name="user-trip"),
    path("api/v1/user/ticket/", ListCreateTicketUserView.as_view(), name="ticket-list"),
    path(
        "api/v1/user/ticket/<int:pk>/",
        RetrieveUpdateTicketUserView.as_view(),
        name="ticket-detail",
    ),
    path("api/v1/trip/<int:pk>/", TripView.as_view(), name="trip"),
]

app/app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)

from app import settings
from core.views import pageForbidden, AjaxGetStationsView, pageNotFound

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/v1/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    path("", include("api.urls")),
    path("", include("core.urls")),
    path("user/", include("user.urls")),
    path("partner/", include("partner.urls")),
    path("select2/", include("django_select2.urls")),
    path("ajax/get_stations/", AjaxGetStationsView.as_view(), name="ajax_get_stations"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include("debug_toolbar.urls"))] + urlpatterns

handler403 = pageForbidden
handler404 = pageNotFound

app/core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path("", home_page, name="home"),
    path("checkout/<int:trip_pk>", checkout, name="checkout"),
]

app/partner/urls.py
from django.urls import path
from partner.views import *

app_name = "partner"

urlpatterns = [
    path("profile/", PartnerProfileView.as_view(), name="profile"),
    path("bus/list/", BusView.as_view(), name="buses"),
    path("bus/create/", CreateBusView.as_view(), name="bus_create"),
    path("trips/", TripView.as_view(), name="trips"),
    path("trip/create/", CreateTripView.as_view(), name="trip_create"),
    path("trip/<int:trip_pk>/update/", UpdateTripView.as_view(), name="trip_update"),
    path("registration/", partner_registration, name="registration"),
    path("sub_accounts/", SubAccountsView.as_view(), name="sub_accounts"),
    path(
        "sub_account_create/",
        partner_subaccount_registration,
        name="sub_account_create",
    ),
    path("station/create/", StationCreateView.as_view(), name="station_create"),
    path("station/list/", StationListView.as_view(), name="station_list"),
]

app/user/urls.py
from django.urls import path
from user.views import *

app_name = "user"

urlpatterns = [
    path("registration/", RegisterUser.as_view(), name="registration"),
    path("login/", LoginUser.as_view(), name="login"),
    path("trips/future/", user_profile, name="future"),
    path("contact/", user_contact, name="contact"),
    path("trips/history/", user_history, name="history"),
    path("ticket/<int:ticket_pk>/return/", ticket_return, name="ticket_return"),
    path("tickets/returned", user_returned_tickets, name="returned_tickets"),
    path("", logout_user, name="logout"),
]

app/templates/partials/nav-bar.html
<div class="container">
    <div class="row">
        <div class="col">
            <nav class="navbar navbar-expand-lg navbar-light">
                <div class="container-fluid p-0">
                    <a class="navbar-brand" href="{% url 'core:home'%}">
                        <svg xmlns="http://www.w3.org/2000/svg" width="1.5em" height="1.5em" fill="currentColor"
                             class="bi bi-bus-front" viewBox="0 0 16 16">
                            <path d="M5 11a1 1 0 1 1-2 0 1 1 0 0 1 2 0m8 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-6-1a1 1 0 1 0 0 2h2a1 1 0 1 0 0-2zm1-6c-1.876 0-3.426.109-4.552.226A.5.5 0 0 0 3 4.723v3.554a.5.5 0 0 0 .448.497C4.574 8.891 6.124 9 8 9c1.876 0 3.426-.109 4.552-.226A.5.5 0 0 0 13 8.277V4.723a.5.5 0 0 0-.448-.497A44.303 44.303 0 0 0 8 4m0-1c-1.837 0-3.353.107-4.448.22a.5.5 0 1 1-.104-.994A44.304 44.304 0 0 1 8 2c1.876 0 3.426.109 4.552.226a.5.5 0 1 1-.104.994A43.306 43.306 0 0 0 8 3"/>
                            <path d="M15 8a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1V2.64c0-1.188-.845-2.232-2.064-2.372A43.61 43.61 0 0 0 8 0C5.9 0 4.208.136 3.064.268 1.845.408 1 1.452 1 2.64V4a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1v3.5c0 .818.393 1.544 1 2v2a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5V14h6v1.5a.5.5 0 0 0 .5.5h2a.5.5 0 0 0 .5-.5v-2c.607-.456 1-1.182 1-2zM8 1c2.056 0 3.71.134 4.822.261.676.078 1.178.66 1.178 1.379v8.86a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 11.5V2.64c0-.72.502-1.301 1.178-1.379A42.611 42.611 0 0 1 8 1"/>
                        </svg>
                        <span class="fw-bold">BusEnjoyer</span>
                    </a>
                    <div>
                        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                            {% if user.is_authenticated %}
                            <li class="nav-item dropdown">
                                {% if user.is_sub_account %}
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="1.5em" height="1.5em"
                                         fill="currentColor" class="bi bi-people" viewBox="0 0 16 16">
                                        <path d="M15 14s1 0 1-1-1-4-5-4-5 3-5 4 1 1 1 1zm-7.978-1L7 12.996c.001-.264.167-1.03.76-1.72C8.312 10.629 9.282 10 11 10c1.717 0 2.687.63 3.24 1.276.593.69.758 1.457.76 1.72l-.008.002-.014.002zM11 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4m3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0M6.936 9.28a6 6 0 0 0-1.23-.247A7 7 0 0 0 5 9c-4 0-5 3-5 4q0 1 1 1h4.216A2.24 2.24 0 0 1 5 13c0-1.01.377-2.042 1.09-2.904.243-.294.526-.569.846-.816M4.92 10A5.5 5.5 0 0 0 4 13H1c0-.26.164-1.03.76-1.724.545-.636 1.492-1.256 3.16-1.275ZM1.5 5.5a3 3 0 1 1 6 0 3 3 0 0 1-6 0m3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4"/>
                                    </svg>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="dropdown-item disabled text-dark">{{user.phone}}</li>
                                    <li><span class="badge rounded-pill bg-info mx-3">Субаккаунт</span></li>
                                    <div class="dropdown-divider"></div>
                                    <li><a class="dropdown-item" href="{% url 'partner:profile' %}">Адмін-панель</a>
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'user:logout' %}">Вийти</a></li>
                                </ul>
                                {% elif user.is_partner %}
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="1.5em" height="1.5em" fill="currentColor"
                                         class="bi bi-person-check" viewBox="0 0 16 16">
                                        <path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7m1.679-4.493-1.335 2.226a.75.75 0 0 1-1.174.144l-.774-.773a.5.5 0 0 1 .708-.708l.547.548 1.17-1.951a.5.5 0 1 1 .858.514M11 5a3 3 0 1 1-6 0 3 3 0 0 1 6 0M8 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4"/>
                                        <path d="M8.256 14a4.5 4.5 0 0 1-.229-1.004H3c.001-.246.154-.986.832-1.664C4.484 10.68 5.711 10 8 10q.39 0 .74.025c.226-.341.496-.65.804-.918Q8.844 9.002 8 9c-5 0-6 3-6 4s1 1 1 1z"/>
                                    </svg>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li class="dropdown-item disabled text-dark">{{user.phone}}</li>
                                    <li><span class="badge rounded-pill bg-info mx-3">Партнер</span></li>
                                    <div class="dropdown-divider"></div>
                                    <li><a class="dropdown-item" href="{% url 'partner:profile' %}">Адмін-панель</a>
                                    </li>
                                    <li><a class="dropdown-item" href="{% url 'user:logout' %}">Вийти</a></li>
                                </ul>
                                {% else %}
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="1.5em" height="1.5em"
                                         fill="currentColor" stroke-width="20" class="bi bi-person" viewBox="0 0 16 16">
                                        <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z"/>
                                    </svg>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'user:contact'%}">{{user.phone}}</a></li>
                                    <div class="dropdown-divider"></div>
                                    <li><a class="dropdown-item" href="{% url 'user:future' %}">Мої поїздки</a></li>
                                    <li><a class="dropdown-item" href="{% url 'user:logout' %}">Вийти</a></li>
                                </ul>
                                {% endif %}
                                {% else %}
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                   data-bs-toggle="dropdown" aria-expanded="false">
                                    <span>Реєстрація</span>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <li><a class="dropdown-item" href="{% url 'user:registration' %}">Реєстрація
                                        користувача</a></li>
                                    <li><a class="dropdown-item" href="{% url 'partner:registration' %}">Реєстрація
                                        партнера</a></li>
                                </ul>
                                <a class="nav-link" href="{% url 'user:login' %}">Логін</a>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
    </div>
</div>