app/api/urls.py
from django.urls import path, include
from rest_framework import routers

from api.views import *

app_name = "api"

bus_router = routers.DefaultRouter()
bus_router.register(r"bus", BusViewSet, basename="bus")
trip_router = routers.DefaultRouter()
trip_router.register(r"trip", TripPartnerViewSet, basename="trip")

urlpatterns = [
    path("api/v1/user/create/", CreateUserView.as_view(), name="user-create"),
    path("api/v1/partner/create/", CreatePartnerView.as_view(), name="partner-create"),
    path("api/v1/token/", CreateTokenView.as_view(), name="token"),
    path("api/v1/user/me/", ManageUserView.as_view(), name="user-me"),
    path("api/v1/partner/me/", ManagePartnerView.as_view(), name="partner-me"),
    path("api/v1/partner/", include(bus_router.urls)),
    path("api/v1/partner/", include(trip_router.urls)),
    path("api/v1/city/", CityView.as_view(), name="city"),
    path(
        "api/v1/partner/station/",
        ListCreateStationView.as_view(),
        name="partner-station",
    ),
    path("api/v1/user/trip/", TripUserView.as_view(), name="user-trip"),
    path("api/v1/user/ticket/", ListCreateTicketUserView.as_view(), name="ticket-list"),
    path(
        "api/v1/user/ticket/<int:pk>/",
        RetrieveUpdateTicketUserView.as_view(),
        name="ticket-detail",
    ),
    path("api/v1/trip/<int:pk>/", TripView.as_view(), name="trip"),
]

app/app/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)

from app import settings
from core.views import pageForbidden, AjaxGetStationsView, pageNotFound

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/v1/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    path("", include("api.urls")),
    path("", include("core.urls")),
    path("user/", include("user.urls")),
    path("partner/", include("partner.urls")),
    path("select2/", include("django_select2.urls")),
    path("ajax/get_stations/", AjaxGetStationsView.as_view(), name="ajax_get_stations"),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include("debug_toolbar.urls"))] + urlpatterns

handler403 = pageForbidden
handler404 = pageNotFound

app/core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path("", home_page, name="home"),
    path("checkout/<int:trip_pk>", checkout, name="checkout"),
]

app/core/forms.py
from datetime import datetime, date
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import *
from phonenumber_field.formfields import PhoneNumberField


class BuyerInfoForm(forms.Form):
    email = forms.EmailField(
        label="E-mail",
        widget=forms.TextInput(
            attrs={
                "placeholder": ("email@gmail.com"),
                "id": "phone",
            }
        ),
    )
    phone = PhoneNumberField(
        label=_("Телефон"),
        widget=forms.TextInput(
            attrs={
                "placeholder": ("+380 __ ___ __ __"),
                "id": "email",
            }
        ),
    )


class PassagerInfoForm(forms.Form):
    first_name = forms.CharField(
        label=_("Ім'я"),
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "first_name",
            }
        ),
    )
    last_name = forms.CharField(
        label=_("Фамілія"),
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "id": "last_name",
            }
        ),
    )


class CitySelectionForm(forms.Form):
    start_point = forms.CharField(
        label=_("Звідки"),
        widget=forms.TextInput(
            attrs={
                "autocomplete": "off",
                "class": "form-control",
                "id": "search_data_start_point",
            }
        ),
    )
    end_point = forms.CharField(
        label=_("Куди"),
        widget=forms.TextInput(
            attrs={
                "autocomplete": "off",
                "class": "form-control",
                "id": "search_data_end_point",
            }
        ),
    )
    date = forms.DateField(
        label=_("Дата поїздки"),
        widget=forms.DateInput(
            attrs={
                "type": "date",
                "class": "form-control datepicker",
                "id": "floatingInputGrid",
                "min": datetime.now().date(),
                "value": datetime.now().strftime("%Y-%m-%d"),
            }
        ),
    )
    passengers_quantity = forms.IntegerField(
        label=_("Кількість пасажирів"),
        min_value=0,
        max_value=10,
        initial=1,
        widget=forms.NumberInput(
            attrs={
                "type": "number",
                "class": "form-control number-input",
                "id": "floatingInputGrid",
            }
        ),
    )

    def clean(self):
        cleaned_data = super().clean()
        start_point = cleaned_data.get("start_point")
        end_point = cleaned_data.get("end_point")

        if start_point and end_point and start_point == end_point:
            raise ValidationError(_("Початковий та кінцевий пункт мають бути різними."))

        return cleaned_data

app/core/views.py
from django.contrib.auth import login, authenticate
from django.core.exceptions import PermissionDenied
from django.http import (
    JsonResponse,
    HttpResponseNotFound,
)
from django.shortcuts import render, redirect
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views import View
from django.core import serializers

from core.forms import *
from core.models import *
from user.forms import RegisterClientForm
from .utils import *


class AjaxGetStationsView(View):
    """
    Ajax View for getting stations relatively to the selected city
    """

    def get(self, request):
        """
        Handle GET requests and return a JSON response with a list of stations.
        """

        city_id = request.GET.get("city_id")
        stations = Station.objects.filter(city_id=city_id)
        station_list = [
            {
                "id": station.id,
                "text": f"{station.station}, {station.street_type} {station.street}, {station.number}, {station.city.city}, {station.city.region} {_('область')}, {station.city.country}",
            }
            for station in stations
        ]
        return JsonResponse({"results": station_list})


def home_page(request):
    """
    View for the home page.
    Handles the logic for displaying and processing the city selection form to find available trips.

    Returns:
        HttpResponse: Rendered home page with the city selection form and available trips.
    """

    queryset = None
    context = {"title": "BusEnjoyer"}

    if request.method == "POST":
        form = CitySelectionForm(request.POST)
        if form.is_valid():
            start_point_str = form.cleaned_data["start_point"]
            end_point_str = form.cleaned_data["end_point"]

            start_point_data = {
                "city": start_point_str.split(",")[0].strip(),
                "region": start_point_str.split(",")[1].replace("область", "").strip(),
                "country": start_point_str.split(",")[2].strip(),
            }

            end_point_data = {
                "city": end_point_str.split(",")[0].strip(),
                "region": end_point_str.split(",")[1].replace("область", "").strip(),
                "country": end_point_str.split(",")[2].strip(),
            }

            start_point = City.objects.get(**start_point_data)
            end_point = City.objects.get(**end_point_data)

            date = form.cleaned_data["date"]
            passengers_quantity = form.cleaned_data["passengers_quantity"]
            request.session["passengers_quantity"] = passengers_quantity
            request.session["start_point"] = start_point.pk
            request.session["end_point"] = end_point.pk
            request.session["date"] = str(date)
            current_time = datetime.now().time()
            context.update(
                {
                    "start_point": start_point,
                    "end_point": end_point,
                    "date": date,
                }
            )
            if date == datetime.now().date():
                queryset = Trip.objects.filter(
                    start_point=start_point,
                    end_point=end_point,
                    timedate_departure__date=date,
                    timedate_departure__time__gt=current_time,
                )
            else:
                queryset = Trip.objects.filter(
                    start_point=start_point,
                    end_point=end_point,
                    timedate_departure__date=date,
                )
            for trip in queryset:
                sold_tickets_count = Ticket.objects.filter(
                    trip=trip, returned=False
                ).count()
                remaining_seats = trip.bus.number_of_seats - sold_tickets_count
                trip.remaining_seats = remaining_seats
                trip.price = trip.price * passengers_quantity
            queryset = [
                trip for trip in queryset if trip.remaining_seats >= passengers_quantity
            ]
        else:
            for key, value in form.errors.items():
                if key != "__all__":
                    form.fields[key].widget.attrs["class"] = "form-control is-invalid"
    else:
        passengers_quantity = request.session.get("passengers_quantity", None)
        start_point = request.session.get("start_point", None)
        end_point = request.session.get("end_point", None)
        date = (
            request.session.get("date")
            if request.session.get("date")
            and request.session.get("date") >= str(timezone.now().date())
            else str(timezone.now().date())
        )

        if passengers_quantity and start_point and end_point and date:
            form = CitySelectionForm(
                initial={
                    "date": date,
                    "passengers_quantity": passengers_quantity,
                    "start_point": str(City.objects.get(pk=start_point)),
                    "end_point": str(City.objects.get(pk=end_point)),
                }
            )
        else:
            form = CitySelectionForm()
    cities = City.objects.all()
    cities_list = serializers.serialize("json", list(cities))
    context.update(
        {
            "cities": cities_list,
            "form": form,
            "queryset": queryset,
        }
    )

    return render(request, "core/index.html", context=context)


def checkout(request, trip_pk):
    """
    View for handling the checkout process.
    Handles the logic for processing ticket purchases, including user authentication,
    form validation, and creating Ticket objects.

    Args:
        request (HttpRequest): The HTTP request object.
        trip_pk (int): The primary key of the selected trip.

    Returns:
        HttpResponse: Redirects to the user's future trips page after successful purchase.
    """

    trip = Trip.objects.get(pk=trip_pk)
    passengers_quantity = request.session.get("passengers_quantity", 1)
    available_seats = (
        trip.bus.number_of_seats
        - Ticket.objects.filter(trip=trip, returned=False).count()
    )
    price = trip.price * passengers_quantity
    if trip.timedate_departure < timezone.now():
        return HttpResponseNotFound()

    if available_seats < passengers_quantity:
        raise PermissionDenied("Not enough available seats")

    if request.method == "POST":
        passenger_forms = [
            PassagerInfoForm(request.POST, prefix=f"passenger_{i}")
            for i in range(passengers_quantity)
        ]
        if not request.user.is_authenticated:
            buyer_form = RegisterClientForm(request.POST)
            if buyer_form.is_valid() and all(
                form.is_valid() for form in passenger_forms
            ):
                new_user = buyer_form.save()

                for i, form in enumerate(passenger_forms):
                    ticket_data = form.cleaned_data  # first_name, last_name
                    ticket_data["user"] = new_user
                    ticket_data["trip_id"] = trip_pk
                    Ticket.objects.create(**ticket_data)

                user = authenticate(
                    request,
                    username=new_user.phone,
                    password=buyer_form.cleaned_data["password1"],
                )
                login(request, user)

        else:
            if all(form.is_valid() for form in passenger_forms):
                for i, form in enumerate(passenger_forms):
                    ticket_data = form.cleaned_data  # first_name, last_name
                    ticket_data["user"] = request.user
                    ticket_data["trip_id"] = trip_pk
                    Ticket.objects.create(**ticket_data)

        return redirect("user:future")

    else:
        if not request.user.is_authenticated:
            buyer_form = RegisterClientForm()
        else:
            buyer_form = None
        passenger_forms = [
            PassagerInfoForm(prefix=f"passenger_{i}")
            for i in range(passengers_quantity)
        ]

    return render(
        request,
        "checkout.html",
        context={
            "buyer_form": buyer_form,
            "passenger_forms": passenger_forms,
            "title": _(
                f"Сплата квитка {trip.start_point.city} - {trip.end_point.city}"
            ),
            "trip": trip,
            "price": price,
        },
    )


def pageForbidden(request, exception):
    """
    View for handling forbidden (403) requests.

    Args:
        request (HttpRequest): The HTTP request object.
        exception: The exception object.

    Returns:
        HttpResponse: Rendered 403 page.
    """

    return render(
        request, "403.html", status=403, context={"title": "Доступ заблоковано"}
    )


def pageNotFound(request, exception):
    """
    View for handling not found (404) requests.

    Args:
        request (HttpRequest): The HTTP request object.
        exception: The exception object.

    Returns:
        HttpResponse: Rendered 404 page.
    """

    return render(
        request, "404.html", status=404, context={"title": "Сторінка не знайдена"}
    )

app/core/templates/core/checkout.html
{% extends  'core/base.html' %}

{% block content %}
<div class="row mt-4">
    <div class="col">
        <span class="fs-4 fw-bold">Оформлення квитка</span>
    </div>
</div>
<form method="post" action="{% url 'core:checkout' trip_pk=trip.pk %}" novalidate>
    {% csrf_token %}
    <div class="row">
        <div class="col-6">
            <!-- Passenger form -->
            {% for form in  passenger_forms %}
            <div class="container mt-4 bg-body shadow-sm py-3 rounded">
                <div class="row">
                    <div class="col">
                        <span class="fw-bold fs-4">Пасажир №{{forloop.counter}}</span>
                    </div>
                </div>
                <div class="row">
                    {% for field in form %}
                        <div class="col-6">
                            <label class="form-label mt-2" for={{field.name}}>{{field.label}}</label>
                            {{field}}
                            {% if field.name in form.errors.keys %}
                                <div class="text-danger small">
                                    {% for f, errors in form.errors.items %}
                                        {% if f == field.name %}
                                            {% for error in errors %}
                                                {{error}}
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
            </div>
            {% endfor %}
        </div>
        <div class="col"> <!-- Карточка рейсу -->
            <div class="container p-0 p-3 mt-4 rounded shadow-sm bg-body">
                <div class="row">
                    <div class="col">
                        <span>
                            Рейс <span class="fw-bold">{{trip.start_point.city}}</span> - <span
                                class="fw-bold">{{trip.end_point.city}}</span>, на <span class="fw-bold">{{trip.timedate_departure}}</span>
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col">
                        Перевізник: <span class="fw-light">{{trip.bus.company}}</span>
                    </div>
                </div>
                <div class="col">
                    Автобус: {{trip.bus.brand}} {{trip.bus.licence_plate}}
                </div>
                <div class="row mb-3">
                    <div class="col">
                        Час в дорозі: <span class="fw-light">{{trip.timedate_arrival|timeuntil:trip.timedate_departure}}</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-2">
                        <span class="fw-bold">{{trip.timedate_departure|time}}</span>
                    </div>
                    <div class="col">
                        <span class="fw-bold">{{trip.start_point.city}}</span>
                    </div>
                </div>
                <div class="row mb-4">
                    <div class="col-2">
                        <span class="fw-light">{{trip.timedate_departure | date:"j b."}}</span>
                    </div>
                    <div class="col">
                        <span class="fw-light">
                            {{trip.departure_station.station}}
                            {{trip.departure_station.street_type|lower}}
                            {{trip.departure_station.street}},
                            {{trip.departure_station.number}}
                        </span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-2">
                        <span class="fw-bold">{{trip.timedate_arrival|time}}</span>
                    </div>
                    <div class="col">
                        <span class="fw-bold">{{trip.end_point.city}}</span>
                    </div>
                </div>
                <div class="row">
                    <div class="col-2">
                        <span class="fw-light">{{trip.timedate_arrival| date:"j b."}}</span>
                    </div>
                    <div class="col">
                        <span class="fw-light">
                            {{trip.arrival_station.station}}
                            {{trip.arrival_station.street_type|lower}}
                            {{trip.arrival_station.street}},
                            {{trip.arrival_station.number}}
                        </span>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% if buyer_form %}
        <div class="row mt-4">
            <span class="fs-4 fw-bold">Інформація про покупця</span>
            <p>Вказуйте коректні e-mail та номер телефону, тому що вони необхідні для ідентифікації користувача, отримання квитка, можливості авторизації в особистому кабінеті та можливості повернути квиток</p>
            <!-- Buyer form -->
            {% for field in buyer_form %}
            <div class="row d-flex justify-content-start">
                <div class="col-4">
                    <label class="form-label mt-2" for={{field.name}}>{{field.label}}</label>
                    <span id={{field.name}}>{{field}}</span>
                    {% if field.name in form.errors.keys %}
                        <div class="text-danger small">
                            {% for f, errors in form.errors.items %}
                                {% if f == field.name %}
                                    {% for error in errors %}
                                        {{error}}
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    {% endif %}

    <div class="row">
        <div class="col">
            <div class="row my-3">
                <div class="col">
                    <span class="fs-4 fw-bold">{{price}} UAH</span>
                </div>
            </div>
            <div class="row">
                <div class="col-4 d-grid">
                    <button type="submit" class="btn btn-block btn-danger text-light">Купити білет</button>
                </div>
            </div>
        </div>
    </div>
</form>
{% endblock %}

app/core/templates/core/index.html
{% extends  'core/base.html' %}

{% block info %}
<div class="container mt-5 mb-4">
    <div class="row d-flex justify-content-center align-items-center">
        <div class="col-1 me-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="5em" height="5em" fill="currentColor" class="bi bi-house-fill"
                 viewBox="0 0 16 16">
                <path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293z"/>
                <path d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293z"/>
            </svg>
        </div>
        <div class="col-3">
            <div class="row">
                <div class="col">
                    <span class="fs-1 fw-bold">BusEnjoyer</span>
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <span class="fw-lighter">
                        Від далеких міст до затишних прибережних поселень
                    </span>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block search %}
{{form.media}}
<div class="container pt-4 pb-3">
    <form method="post" action="{% url 'core:home'%}" novalidate>
        {% csrf_token %}
        {% include 'core/includes/all_form_error.html'%}
        <div class="row">
            <div class="col-md-10 col-12">
                    <div class="row gx-0 justify-content-center">
                        {% for f in form %}
                            {% if f.label != "Start point pk" and f.label != "End point pk" %}
                                <div class="col-md-3 col-12"> <!-- Поля формы-->
                                        <div class="form-floating">
                                            {{ f }}
                                            <label for="floatingInputGrid">{{f.label}}</label>
                                        </div>
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
            </div>
            <div class="col-md-2 col-12 ps-md-0">
                <button type="submit" class="btn btn-danger text-light w-100 h-100">Пошук</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

{% block tickets %}
<div class="container">
    {% if request.method == "GET" %}
    <div class="row mt-4">
        <div class="col">
            <span class="fs-2 fw-bold">
                Квитки на автобус
            </span>
            <br>
            <span class="fw-lighter fs-5">
                По Україні
            </span>
        </div>
    </div>
    <div class="row mt-5 text-center">
        <div class="col-3">
            <div class="row">
                <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-calendar-date" viewBox="0 0 16 16">
                    <path d="M6.445 11.688V6.354h-.633A12.6 12.6 0 0 0 4.5 7.16v.695c.375-.257.969-.62 1.258-.777h.012v4.61h.675zm1.188-1.305c.047.64.594 1.406 1.703 1.406 1.258 0 2-1.066 2-2.871 0-1.934-.781-2.668-1.953-2.668-.926 0-1.797.672-1.797 1.809 0 1.16.824 1.77 1.676 1.77.746 0 1.23-.376 1.383-.79h.027c-.004 1.316-.461 2.164-1.305 2.164-.664 0-1.008-.45-1.05-.82h-.684zm2.953-2.317c0 .696-.559 1.18-1.184 1.18-.601 0-1.144-.383-1.144-1.2 0-.823.582-1.21 1.168-1.21.633 0 1.16.398 1.16 1.23"/>
                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5M1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4z"/>
                </svg>
            </div>
            <div class="row p-3">
                <span>Плануйте поїздки заздалегідь з нашим гнучким розкладом.</span>
            </div>
        </div>
        <div class="col-3">
            <div class="row">
                <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-signpost-2" viewBox="0 0 16 16">
                     <path d="M7 1.414V2H2a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h5v1H2.5a1 1 0 0 0-.8.4L.725 8.7a.5.5 0 0 0 0 .6l.975 1.3a1 1 0 0 0 .8.4H7v5h2v-5h5a1 1 0 0 0 1-1V8a1 1 0 0 0-1-1H9V6h4.5a1 1 0 0 0 .8-.4l.975-1.3a.5.5 0 0 0 0-.6L14.3 2.4a1 1 0 0 0-.8-.4H9v-.586a1 1 0 0 0-2 0zM13.5 3l.75 1-.75 1H2V3zm.5 5v2H2.5l-.75-1 .75-1z"/>
                </svg>
            </div>
            <div class="row p-3">
                <span>Об'єднуємо міста у зручних маршрутах.</span>
            </div>
        </div>
        <div class="col-3">
            <div class="row">
                <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-ticket" viewBox="0 0 16 16">
                     <path d="M0 4.5A1.5 1.5 0 0 1 1.5 3h13A1.5 1.5 0 0 1 16 4.5V6a.5.5 0 0 1-.5.5 1.5 1.5 0 0 0 0 3 .5.5 0 0 1 .5.5v1.5a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 11.5V10a.5.5 0 0 1 .5-.5 1.5 1.5 0 1 0 0-3A.5.5 0 0 1 0 6zM1.5 4a.5.5 0 0 0-.5.5v1.05a2.5 2.5 0 0 1 0 4.9v1.05a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-1.05a2.5 2.5 0 0 1 0-4.9V4.5a.5.5 0 0 0-.5-.5z"/>
                </svg>
            </div>
            <div class="row p-3">
                <span>Комфорт та зручність в одному дотику!</span>
            </div>
        </div>
        <div class="col-3">
            <div class="row">
                <svg xmlns="http://www.w3.org/2000/svg" width="2em" height="3em" fill="currentColor" class="bi bi-person-lines-fill" viewBox="0 0 16 16">
                    <path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5m.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1z"/>
                </svg>
            </div>
            <div class="row p-3">
                <span>Особистий кабінет для зручностей. Зберігайте маршрути та слідкуйте за своїми поїздками.</span>
            </div>
        </div>
    </div>
    {% else %}
    <h4 class="mb-3 mt-3">Розклад автобусів {{start_point.city}} - {{end_point.city}} на {{date}} <br></h4>
    {% if queryset|length > 0 %}
    {% for trip in queryset %}
        {% include 'core/includes/ticket.html' with trip=trip %}
    {% endfor %}
    {% else %}
            <div class="container">
                <div class="row py-3 d-flex justify-content-center align-items-center">
                    <div class="col-1 text-muted">
                        <svg xmlns="http://www.w3.org/2000/svg" width="3em" height="3em" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                            <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0"/>
                        </svg>
                    </div>
                    <div class="col-5">
                        <div class="row">
                            <h2 class="text-muted"> Квитки не знайдені </h2>
                        </div>
                        <div class="row">
                            <span class="fw-lighter text-muted">Ми не знайшли квитків на обрану дату.</span>
                        </div>
                    </div>
                </div>
            </div>
    {% endif %}
    {% endif %}
</div>

<script>
    var citiesData = JSON.parse('{{ cities|safe}}');
    var availableCities = [];

    var searchInput_1 = document.getElementById('search_data_start_point');
    var searchInput_2 = document.getElementById('search_data_end_point');

    function autocompleteSetup(source, inputElement) {
        inputElement.addEventListener('input', function () {
            var inputValue = this.value;
            var matches = source.filter(function (item) {
                return item.city.toLowerCase().startsWith(inputValue.toLowerCase());
            });

            if (matches.length > 0) {
                var autocompleteList = document.createElement('ul');
                autocompleteList.classList.add('autocomplete-list');

                matches.forEach(function (match) {
                    var listItem = document.createElement('li');
                    listItem.textContent = match.city + ', ' + match.region + ' область, ' + match.country;
                    autocompleteList.appendChild(listItem);
                });

                removeExistingAutocomplete();

                this.parentNode.appendChild(autocompleteList);

                autocompleteList.addEventListener('click', function (e) {
                    if (e.target.tagName === 'LI') {
                        inputElement.value = e.target.textContent;
                        removeExistingAutocomplete();
                    }
                });
            } else {
                removeExistingAutocomplete();
            }
        });

        document.addEventListener('click', function (e) {
            if (!inputElement.contains(e.target)) {
                removeExistingAutocomplete();
            }
        });

        function removeExistingAutocomplete() {
            var existingAutocomplete = document.querySelector('.autocomplete-list');
            if (existingAutocomplete) {
                existingAutocomplete.remove();
            }
        }
    }

    // Setup autocomplete for the first field
    availableCities = citiesData.map(function (item) {
        return {
            city: item.fields.city,
            region: item.fields.region,
            country: item.fields.country,
        };
    });
    autocompleteSetup(availableCities, searchInput_1);

    // Setup autocomplete for the second field
    autocompleteSetup(availableCities, searchInput_2);
</script>
{% endblock %}